{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flux.fullname" . }}
  labels:
    {{- include "flux.labels" . | nindent 4 }}
type: Opaque
data:
  FLUX_API_KEY_PEPPER: {{ .Values.secrets.apiKeyPepper | b64enc | quote }}
  FLUX_DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
{{- end }}
